---
#
# Copyright 2022 Red Hat, Project Atmosphere
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

- name: Create a snapshot by copying an existing managed disk
  vars:
    managed_disk_name: "{{ dataDisk.managedDisk.id.split('/') | last }}"
    snap_id: "{{ managed_disk_name }}_{{ azure_rm_snapshot_suffix | default('default') }}"
  azure.azcollection.azure_rm_snapshot:
    resource_group: "{{ disks.instance.resourcegroup_name }}"
    name: "{{ snap_id }}"
    location: "{{ disks.instance.location }}"
    creation_data:
      create_option: "Copy"
      source_id: "{{ dataDisk.managedDisk.id }}"
