---
#
# Copyright 2022 Red Hat, Project Atmosphere
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

# - name: Get instances metadata
#   hosts: all:!localhost
#   gather_facts: true
#   become: true
#   become_user: root
#   no_log: "{{ molecule_no_log }}"
#   vars:
#     metadata_server: http://169.254.169.254/metadata
#     metadata_instance_endpoint: /instance?api-version=2021-12-13

#   tasks:
#     - name: Get instance metadata
#       ansible.builtin.uri:
#         url: "{{ metadata_server }}{{ metadata_instance_endpoint }}"
#         headers:
#           Metadata: true
#       register: metadata_instance_info

- name: Backup
  hosts: localhost
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  # vars:
  #   azure_molecule_servers:
  #     results: []
  #     changed: false

  tasks:
    # - name: Get facts managed disks
    #   ansible.builtin.include_tasks: ./azure/tasks/get_managed_disks.yml
    #   loop: "{{ molecule_yml.platforms }}"
    #   loop_control:
    #     loop_var: instance
    #   register: managed_disks

    # - name: Backup managed disks
    #   ansible.builtin.include_tasks: azure/tasks/backup_managed_disks.yml
    #   with_items: "{{ managed_disks.results }}"
    #   loop_control:
    #     loop_var: disks
    - name: Include default variables
      ansible.builtin.include_vars:
        file: azure/defaults/main.yml

    - name: Backup managed disks for each instance
      ansible.builtin.include_tasks: azure/tasks/backup_instance.yml
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: instance

